name: Cut Release Tag
author: Hiroaki Kobayashi
description: Automatically create tags from the VERSION file
inputs:
  force:
    description: Replace an existing tag
    required: false
    default: false
  message:
    description: Tag message, __VERSION__ will replace its version number
    required: false
    default: release __VERSION__
  only_major_version:
    description: Use only major version
    required: false
    default: false
  prefix:
    description: Prefix for release tag
    required: false
    default: v
  suffix:
    description: Suffix for release tag
    required: false
    default: ''
  hostname:
    description: Hostname for yum repo
    required: false
    default: ''
  username:
    description: username for yum repo
    required: false
    default: ''
  password:
    description: password for yum repor
    required: false
    default: ''
outputs:
  tag:
    description: Name for release tag
runs:
  using: docker
  image: Dockerfile
branding:
  color: orange
  icon: tag
